import {
  Anchor,
  Aperture,
  AtSign,
  Atom,
  Baby,
  Banknote,
  Beer,
  Bike,
  Bird,
  Blocks,
  BookOpen,
  Bot,
  Braces,
  Brain,
  Briefcase,
  Brush,
  Bug,
  Building2,
  Calendar,
  Camera,
  Car,
  Cat,
  ChartLine,
  ChartPie,
  Cherry,
  Clapperboard,
  ClipboardList,
  Cloud,
  Code,
  Coffee,
  Compass,
  Cpu,
  Crown,
  Database,
  Dice5,
  Dog,
  Drama,
  Dumbbell,
  Feather,
  Film,
  Fish,
  FlaskConical,
  Flame,
  Flower2,
  Gamepad2,
  Gem,
  Ghost,
  Gift,
  GitBranch,
  Globe,
  GraduationCap,
  Guitar,
  Handshake,
  Headphones,
  Heart,
  House,
  IceCreamCone,
  Inbox,
  Landmark,
  Languages,
  Leaf,
  Library,
  Lightbulb,
  Mail,
  Map,
  Megaphone,
  MessageCircle,
  Mic,
  Microscope,
  Moon,
  Mountain,
  Music,
  Newspaper,
  Notebook,
  Orbit,
  Palette,
  PartyPopper,
  PawPrint,
  PenTool,
  Pizza,
  Plane,
  Popcorn,
  Presentation,
  Rainbow,
  Receipt,
  Rocket,
  Scale,
  Server,
  Shapes,
  ShoppingBag,
  Skull,
  Smile,
  Snowflake,
  Sparkles,
  Sprout,
  Star,
  Sun,
  Swords,
  Target,
  Tent,
  Terminal,
  TreePine,
  Trophy,
  Tv,
  Users,
  Utensils,
  Wallet,
  WandSparkles,
  Waves,
  Wine,
  Zap,
  type LucideIcon
} from 'lucide-react'
import { ICON_PREFIX } from '../../shared/theme'

/** The Space icon library: line icons by theme. Stored on a Space as `icon:<Name>`. */
export const ICON_GROUPS: { name: string; icons: Record<string, LucideIcon> }[] = [
  {
    name: 'Work',
    icons: {
      Briefcase,
      Building2,
      Landmark,
      ChartLine,
      ChartPie,
      Presentation,
      Calendar,
      ClipboardList,
      Target,
      Handshake,
      Mail,
      Inbox,
      Receipt,
      Wallet,
      Banknote,
      Scale
    }
  },
  {
    name: 'Create',
    icons: {
      Palette,
      PenTool,
      Brush,
      Camera,
      Aperture,
      Film,
      Clapperboard,
      Music,
      Mic,
      Shapes,
      Sparkles,
      WandSparkles,
      Lightbulb,
      Feather
    }
  },
  {
    name: 'Code',
    icons: {
      Code,
      Terminal,
      Braces,
      Bug,
      Cpu,
      Database,
      Server,
      Cloud,
      GitBranch,
      Bot,
      Blocks,
      FlaskConical,
      Atom
    }
  },
  {
    name: 'Learn',
    icons: {
      BookOpen,
      GraduationCap,
      Library,
      Notebook,
      Brain,
      Microscope,
      Globe,
      Languages,
      Newspaper
    }
  },
  {
    name: 'Life',
    icons: {
      House,
      Heart,
      Coffee,
      Utensils,
      ShoppingBag,
      Dumbbell,
      Bike,
      Plane,
      Car,
      Map,
      Compass,
      Tent,
      Mountain,
      TreePine,
      Leaf,
      Sprout,
      Flower2,
      Waves,
      Sun,
      Moon,
      Baby,
      PawPrint,
      Gift
    }
  },
  {
    name: 'Fun',
    icons: {
      Gamepad2,
      Dice5,
      Trophy,
      Flame,
      Zap,
      Star,
      Crown,
      Gem,
      Rocket,
      Orbit,
      Ghost,
      Skull,
      Swords,
      Drama,
      PartyPopper,
      Popcorn,
      Pizza,
      IceCreamCone,
      Cherry,
      Wine,
      Beer,
      Cat,
      Dog,
      Fish,
      Bird,
      Rainbow,
      Snowflake,
      Anchor,
      Tv,
      Headphones,
      Guitar
    }
  },
  { name: 'People', icons: { Users, MessageCircle, Smile, Megaphone, AtSign } }
]

const ALL: Record<string, LucideIcon> = Object.assign({}, ...ICON_GROUPS.map((g) => g.icons))

/** A Space's icon: a library icon, or an emoji as typed. */
export function SpaceIcon({ icon, size = 16 }: { icon: string; size?: number }): React.JSX.Element {
  if (!icon.startsWith(ICON_PREFIX)) return <span style={{ fontSize: size - 2 }}>{icon}</span>
  const Icon = ALL[icon.slice(ICON_PREFIX.length)] ?? Sparkles
  return <Icon size={size} strokeWidth={1.75} aria-hidden />
}
